# ai_medical_checker/.streamlit/secrets.toml

# This file is used to securely store your API keys.
# Streamlit will automatically load these secrets for use in your application.

# You MUST replace these with your actual keys and URLs.

# Hugging Face API for Medical NER
HUGGING_FACE_API_KEY = "your-actual-hugging-face-api-key"
HUGGING_FACE_NER_URL = "https://api-inference.huggingface.co/models/samant/medical-ner"

# Placeholder for ibm-granite/granite-3.3-8b-instruct
# A real API call to a large model like this would require a specific endpoint.
IBM_GRANITE_URL = "https://api-inference.huggingface.co/models/ibm-granite/granite-3.3-8b-instruct"
